const productAuth = require("./../auth");
const auth = require("./../userauth");
const userControl = require('../controllers/userController');
const productControl = require('../controllers/productController');
const imageControl = require('../controllers/imageController');
const upload = require("./../upload");
module.exports = (app) => {
    app.post("/v2/user", userControl.createUser);
    app.get("/v2/user/:userId", auth, userControl.getUser);
    app.put("/v2/user/:userId", auth, userControl.updateUser);
    app.post("/v2/product", productAuth, productControl.createProduct);
    app.get("/v2/product/:productId", productControl.getProduct);
    app.delete("/v2/product/:productId", productAuth, productControl.deleteProduct);
    app.put("/v2/product/:productId", productAuth, productControl.updateProduct);
    app.patch("/v2/product/:productId", productAuth, productControl.updatePatchProduct);
    app.get("/v2/product/:productId/image", productAuth, imageControl.getAllImages);
    app.get("/v2/product/:productId/image/:imageId", productAuth, imageControl.getImage);
    app.post("/v2/product/:productId/image", productAuth, upload.single("image"), imageControl.addImage);
    app.delete("/v2/product/:productId/image/:imageId", productAuth, imageControl.deleteImage);
};